# Generated by Django 6.0.3 on 2026-03-25 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('birth_date', models.DateField()),
                ('subscription_type', models.CharField(choices=[('basic', 'Базовый'), ('standard', 'Стандарт'), ('premium', 'Премиум')], default='basic', max_length=20)),
                ('subscription_end', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('visits_count', models.IntegerField(default=0)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
    ]
